version: '3'

services:
   texo-test-api:
      build:
         context: .
         dockerfile: ./src/api/Dockerfile
      image: texo-test-api:latest
      ports:
         - '8080:8080'
      volumes:
         - ./src/api:/usr/src/app/api
         - /usr/src/app/node_modules
      environment:
         - NODE_ENV=development
      command: sh -c "yarn test && yarn dev"
